export type BrandCategory =
  | "luxe"
  | "createur"
  | "sport"
  | "enfant"
  | "eco"
  | "tendance";

export type PriceRange = "\u20AC" | "\u20AC\u20AC" | "\u20AC\u20AC\u20AC" | "\u20AC\u20AC\u20AC\u20AC";

export interface Brand {
  name: string;
  slug: string;
  image: string | null;
  heroImage?: string;
  country: string;
  countryFlag: string;
  priceRange: PriceRange;
  categories: BrandCategory[];
  french: boolean;
  featured?: boolean;
  badge?: "Tendance" | "Nouveaut\u00E9" | "Exclusivit\u00E9";
  description?: string;
  website?: string;
  ecoResponsible?: boolean;
  artisanal?: boolean;
}

export const categoryLabels: Record<BrandCategory, string> = {
  luxe: "Luxe",
  createur: "Cr\u00E9ateurs",
  sport: "Sport & Outdoor",
  enfant: "Enfant",
  eco: "\u00C9co-responsable",
  tendance: "Tendance",
};

export const brands: Brand[] = [
  // LUXE & CRÉATEURS
  {
    name: "Gucci",
    slug: "gucci",
    image: "/images/marques/gucci.png",
    heroImage: "/images/produits/gucci-campagne.jpg",
    country: "Italie",
    countryFlag: "\uD83C\uDDEE\uD83C\uDDF9",
    priceRange: "\u20AC\u20AC\u20AC\u20AC",
    categories: ["luxe"],
    french: false,
    description: "Maison de luxe italienne fond\u00E9e en 1921. Lunettes au design audacieux et logo double-G iconique.",
  },
  {
    name: "Chlo\u00E9",
    slug: "chloe",
    image: "/images/marques/chloe.png",
    heroImage: "/images/produits/chloe-tendance.jpg",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC\u20AC\u20AC",
    categories: ["luxe"],
    french: true,
    description: "Maison fran\u00E7aise fond\u00E9e en 1952, synonyme de f\u00E9minit\u00E9 boh\u00E8me chic.",
  },
  {
    name: "Oliver Peoples",
    slug: "oliver-peoples",
    image: "/images/marques/oliver-peoples.jpg",
    heroImage: "/images/produits/steve-mcqueen.webp",
    country: "USA",
    countryFlag: "\uD83C\uDDFA\uD83C\uDDF8",
    priceRange: "\u20AC\u20AC\u20AC\u20AC",
    categories: ["luxe", "createur"],
    french: false,
    description: "Marque de luxe californienne fond\u00E9e en 1987. Esth\u00E9tique vintage raffin\u00E9e.",
  },
  {
    name: "Persol",
    slug: "persol",
    image: "/images/marques/persol.webp",
    heroImage: "/images/produits/persol.webp",
    country: "Italie",
    countryFlag: "\uD83C\uDDEE\uD83C\uDDF9",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["luxe"],
    french: false,
    description: "Ic\u00F4ne du savoir-faire artisanal italien depuis 1917. C\u00E9l\u00E8bre pour sa fl\u00E8che lat\u00E9rale.",
  },
  {
    name: "MOSCOT Eyewear",
    slug: "moscot-eyewear",
    image: "/images/marques/moscot.jpg",
    heroImage: "/images/produits/moscot-miltzen.jpg",
    country: "USA",
    countryFlag: "\uD83C\uDDFA\uD83C\uDDF8",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["createur", "tendance"],
    french: false,
    featured: true,
    badge: "Tendance",
    description: "Montures iconiques new-yorkaises depuis 1915, h\u00E9ritage de cinq g\u00E9n\u00E9rations.",
  },
  {
    name: "Isabel Marant",
    slug: "isabel-marant",
    image: "/images/marques/isabel-marant.png",
    heroImage: "/images/produits/isabel-marant-campagne.jpg",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["luxe", "createur"],
    french: true,
    description: "Style audacieux m\u00EAlant luxe fran\u00E7ais et \u00E9l\u00E9gance contemporaine.",
  },
  {
    name: "Fran\u00E7ois Pinton",
    slug: "francois-pinton",
    image: "/images/marques/francois-pinton.png",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["luxe", "createur"],
    french: true,
    artisanal: true,
    description: "Maison fond\u00E9e en 1932, a habill\u00E9 Grace Kelly et Jackie Kennedy.",
  },
  {
    name: "Pierre Cardin",
    slug: "pierre-cardin",
    image: "/images/marques/pierre-cardin.png",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC",
    categories: ["tendance"],
    french: true,
    description: "Maison de mode fran\u00E7aise fond\u00E9e en 1950, design avant-gardiste.",
  },

  // CRÉATEURS FRANÇAIS
  {
    name: "Caroline Abram",
    slug: "caroline-abram",
    image: "/images/marques/caroline-abram.jpg",
    heroImage: "/images/produits/caroline-abram-patchwork.jpg",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC",
    categories: ["createur"],
    french: true,
    description: "Cr\u00E9atrice parisienne, montures r\u00E9tro-glamour inspir\u00E9es des ann\u00E9es 50-60.",
  },
  {
    name: "Jean-Fran\u00E7ois Rey",
    slug: "jean-francois-rey",
    image: "/images/marques/jean-francois-rey.jpg",
    heroImage: "/images/produits/jfrey.jpg",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["createur"],
    french: true,
    artisanal: true,
    description: "Cr\u00E9ateur avant-gardiste du Jura, propri\u00E9taire de l\u2019usine Ellaps.",
  },
  {
    name: "Nathalie Blanc",
    slug: "nathalie-blanc",
    image: "/images/marques/nathalie-blanc.webp",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["createur"],
    french: true,
    artisanal: true,
    description: "Laur\u00E9ate du Silmo d\u2019Or 2018, dorure or 22 carats, verres Zeiss.",
  },
  {
    name: "Monsieur Blanc",
    slug: "monsieur-blanc",
    image: "/images/marques/monsieur-blanc.webp",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["createur"],
    french: true,
    artisanal: true,
    description: "Collection masculine de Maison Nathalie Blanc, titane japonais.",
  },
  {
    name: "Volte Face",
    slug: "volte-face",
    image: "/images/marques/volte-face.png",
    heroImage: "/images/produits/volte-face.jpg",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["createur"],
    french: true,
    artisanal: true,
    description: "N\u00E9e en 1997, d\u00E9velopp\u00E9e par le studio J.F. Rey. Inspir\u00E9e de la joaillerie.",
  },
  {
    name: "Tarian",
    slug: "tarian",
    image: "/images/marques/tarian.jpg",
    heroImage: "/images/produits/tarian.jpg",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["createur"],
    french: true,
    artisanal: true,
    description: "Triple laur\u00E9at du Silmo d\u2019Or. Micro-\u00E9ditions limit\u00E9es \u00E0 500 paires.",
  },
  {
    name: "Roussilhe",
    slug: "roussilhe",
    image: "/images/marques/roussilhe.jpg",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC",
    categories: ["createur"],
    french: true,
    artisanal: true,
    description: "Manufacture du Jura depuis 1979, label Origine France Garantie.",
  },
  {
    name: "Sarah Lavoine",
    slug: "sarah-lavoine",
    image: "/images/marques/sarah-lavoine.jpg",
    heroImage: "/images/produits/sarah-lavoisine-roussilhe.jpg",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["createur"],
    french: true,
    artisanal: true,
    ecoResponsible: true,
    description: "Collaboration avec Ateliers Roussilhe, ac\u00E9tate biologique.",
  },
  {
    name: "Peter and May",
    slug: "peter-and-may",
    image: "/images/marques/peter-and-may.jpg",
    heroImage: "/images/produits/peter-and-may.jpg",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["createur"],
    french: true,
    description: "Marque parisienne ind\u00E9pendante fond\u00E9e en 2012, luxe discret.",
  },
  {
    name: "Noego",
    slug: "noego",
    image: "/images/marques/noego.jpg",
    heroImage: "/images/produits/noego-parasite.jpg",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["createur"],
    french: true,
    description: "Collection avant-gardiste de Hugo Martin, plus de 20 ans de savoir-faire.",
  },
  {
    name: "Oxibis",
    slug: "oxibis",
    image: "/images/marques/oxibis.jpg",
    heroImage: "/images/produits/oxibis.jpg",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC",
    categories: ["createur"],
    french: true,
    description: "Fond\u00E9e en 1992 dans le Jura, label Origine France Garantie.",
  },
  {
    name: "Dilem",
    slug: "dilem",
    image: "/images/marques/dilem.png",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC",
    categories: ["createur"],
    french: true,
    description: "Syst\u00E8me brevet\u00E9 de branches interchangeables depuis 2006.",
  },
  {
    name: "Woow",
    slug: "woow",
    image: "/images/marques/woow.gif",
    heroImage: "/images/produits/woow.gif",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC",
    categories: ["createur", "tendance"],
    french: true,
    description: "Collection ludique avec messages cach\u00E9s au bout des branches.",
  },
  {
    name: "Freakshow",
    slug: "freakshow",
    image: "/images/marques/freakshow.png",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC",
    categories: ["createur"],
    french: true,
    description: "Marque parisienne \u00E0 l\u2019esprit arty, inspir\u00E9e du cin\u00E9ma hollywoodien.",
  },
  {
    name: "Mazette",
    slug: "mazette",
    image: "/images/marques/mazette.png",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC",
    categories: ["createur"],
    french: true,
    description: "Montures r\u00E9tro, color\u00E9es et l\u00E9g\u00E8res \u00E0 prix tr\u00E8s abordable.",
  },
  {
    name: "Lou Cr\u00E9ation",
    slug: "lou-creation",
    image: "/images/marques/lou-creation.jpg",
    heroImage: "/images/produits/lyleoo.jpeg",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC",
    categories: ["createur"],
    french: true,
    description: "Marque du Var fond\u00E9e en 2015 par un fr\u00E8re et une s\u0153ur.",
  },
  {
    name: "Osmose",
    slug: "osmose",
    image: "/images/marques/osmose.jpg",
    heroImage: "/images/produits/osmose.jpg",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC",
    categories: ["createur"],
    french: true,
    description: "Con\u00E7ue en Occitanie depuis 2009, bon rapport qualit\u00E9-prix.",
  },
  {
    name: "Minima",
    slug: "minima",
    image: "/images/marques/minima.jpg",
    heroImage: "/images/produits/minima-femme.jpg",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["createur"],
    french: true,
    description: "Pionni\u00E8re du titane en France depuis 1989, montures ultra-l\u00E9g\u00E8res.",
  },
  {
    name: "Brett Eyewear",
    slug: "brett-eyewear",
    image: "/images/marques/brett-eyewear.webp",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC",
    categories: ["createur"],
    french: true,
    artisanal: true,
    description: "Marque masculine du Jura cr\u00E9\u00E9e en 2019, nomin\u00E9e 3 fois au Silmo d\u2019Or.",
  },
  {
    name: "Cl\u00E9mence et Margaux",
    slug: "clemence-et-margaux",
    image: "/images/marques/clemence-et-margaux.jpg",
    heroImage: "/images/produits/clemence-margaux.jpg",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC",
    categories: ["createur"],
    french: true,
    description: "Montures f\u00E9minines en ac\u00E9tate et m\u00E9tal, tradition et modernit\u00E9.",
  },
  {
    name: "Ancet & Fayolle",
    slug: "ancet-fayolle",
    image: "/images/marques/ancet-fayolle.jpg",
    heroImage: "/images/produits/ancet-fayolle.jpg",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["createur"],
    french: true,
    artisanal: true,
    description: "Marque lyonnaise n\u00E9e en 2022, montures artisanales en titane et bois.",
  },
  {
    name: "Plein les Mirettes",
    slug: "plein-les-mirettes",
    image: "/images/marques/plein-les-mirettes.jpg",
    heroImage: "/images/produits/plein-les-mirettes.jpg",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["createur"],
    french: true,
    artisanal: true,
    description: "Manufacture normande, s\u00E9ries limit\u00E9es \u00E0 75 pi\u00E8ces par couleur.",
  },
  {
    name: "T\u00EAte \u00E0 Lunettes",
    slug: "tete-a-lunettes",
    image: "/images/marques/tete-a-lunettes.jpg",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC",
    categories: ["enfant"],
    french: true,
    description: "Collection enfants de Caroline Abram, laur\u00E9ate du Silmo d\u2019Or enfant.",
  },
  {
    name: "Charles Stone",
    slug: "charles-stone",
    image: "/images/marques/charles-stone.png",
    country: "UK",
    countryFlag: "\uD83C\uDDEC\uD83C\uDDE7",
    priceRange: "\u20AC",
    categories: ["tendance"],
    french: false,
    description: "Design r\u00E9tro urbain new-yorkais, couleurs vibrantes \u00E0 prix abordable.",
  },

  // ÉCO-RESPONSABLE
  {
    name: "Friendly Frenchy",
    slug: "friendly-frenchy",
    image: "/images/marques/friendly-frenchy.jpg",
    heroImage: "/images/produits/friendly-frenchy.jpg",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC",
    categories: ["eco", "createur", "tendance"],
    french: true,
    ecoResponsible: true,
    artisanal: true,
    featured: true,
    badge: "Nouveaut\u00E9",
    description: "Pionni\u00E8re des lunettes en coquillages recycl\u00E9s, 0% p\u00E9trole, 100% fran\u00E7aise.",
  },
  {
    name: "Cl\u00E9ment Lunetier",
    slug: "clement-lunetier",
    image: "/images/marques/clement-lunetier.jpg",
    heroImage: "/images/produits/clement-lunetier.jpg",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["eco", "createur"],
    french: true,
    ecoResponsible: true,
    artisanal: true,
    description: "Atelier artisanal strasbourgeois, montures en bois et bio-ac\u00E9tate.",
  },
  {
    name: "Shelter",
    slug: "shelter",
    image: "/images/marques/shelter.jpg",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["eco", "createur"],
    french: true,
    ecoResponsible: true,
    artisanal: true,
    description: "Manufacture d\u2019Annecy, laur\u00E9ate du Silmo d\u2019Or 2022, bois et bio-ac\u00E9tate.",
  },
  {
    name: "Eco",
    slug: "eco",
    image: "/images/marques/eco.webp",
    heroImage: "/images/produits/elevate-campaign.webp",
    country: "USA",
    countryFlag: "\uD83C\uDDFA\uD83C\uDDF8",
    priceRange: "\u20AC\u20AC",
    categories: ["eco"],
    french: false,
    ecoResponsible: true,
    description: "95% mat\u00E9riaux recycl\u00E9s, un arbre plant\u00E9 par monture vendue.",
  },
  {
    name: "La Brique & la Violette",
    slug: "la-brique-et-la-violette",
    image: "/images/marques/la-brique-et-la-violette.png",
    heroImage: "/images/produits/collection.jpg",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC",
    categories: ["eco", "createur", "tendance"],
    french: true,
    ecoResponsible: true,
    artisanal: true,
    featured: true,
    badge: "Exclusivit\u00E9",
    description: "Cr\u00E9ations artisanales toulousaines, production \u00E0 la commande.",
  },
  {
    name: "Modo",
    slug: "modo",
    image: "/images/marques/modo.jpg",
    heroImage: "/images/produits/modo-titanium.jpg",
    country: "USA",
    countryFlag: "\uD83C\uDDFA\uD83C\uDDF8",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["eco", "createur"],
    french: false,
    ecoResponsible: true,
    description: "Marque new-yorkaise, fusion de design italien et minimalisme scandinave.",
  },

  // CRÉATEURS INTERNATIONAUX
  {
    name: "Etnia Barcelona",
    slug: "etnia-barcelona",
    image: "/images/marques/etnia-barcelona.jpg",
    heroImage: "/images/produits/etnia-barcelona.jpg",
    country: "Espagne",
    countryFlag: "\uD83C\uDDEA\uD83C\uDDF8",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["createur", "tendance"],
    french: false,
    featured: true,
    badge: "Tendance",
    description: "Marque ind\u00E9pendante barcelonaise, h\u00E9ritage artisanal familial.",
  },
  {
    name: "GIGI Studios",
    slug: "gigi-studios",
    image: "/images/marques/gigi-studios.jpg",
    heroImage: "/images/produits/gigi-studios.jpg",
    country: "Espagne",
    countryFlag: "\uD83C\uDDEA\uD83C\uDDF8",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["createur"],
    french: false,
    artisanal: true,
    description: "Maison familiale barcelonaise fond\u00E9e en 1962.",
  },
  {
    name: "Kaleos",
    slug: "kaleos",
    image: "/images/marques/kaleos.jpg",
    heroImage: "/images/produits/kaleos.jpg",
    country: "Espagne",
    countryFlag: "\uD83C\uDDEA\uD83C\uDDF8",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["createur", "tendance"],
    french: false,
    featured: true,
    badge: "Tendance",
    description: "Design contemporain, mat\u00E9riaux premium, assemblage artisanal.",
  },
  {
    name: "Kyme",
    slug: "kyme",
    image: "/images/marques/kyme.png",
    heroImage: "/images/produits/kyme.webp",
    country: "Italie",
    countryFlag: "\uD83C\uDDEE\uD83C\uDDF9",
    priceRange: "\u20AC\u20AC",
    categories: ["createur"],
    french: false,
    artisanal: true,
    description: "100% made in Italy, ac\u00E9tate Mazzucchelli artisanal.",
  },
  {
    name: "Talla Eyewear",
    slug: "talla-eyewear",
    image: "/images/marques/talla.png",
    heroImage: "/images/produits/talla.jpg",
    country: "Italie",
    countryFlag: "\uD83C\uDDEE\uD83C\uDDF9",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["createur"],
    french: false,
    artisanal: true,
    description: "Marque masculine de luxe, fabriqu\u00E9e main en Italie.",
  },
  {
    name: "Orgreen",
    slug: "orgreen",
    image: "/images/marques/orgreen.webp",
    country: "Danemark",
    countryFlag: "\uD83C\uDDE9\uD83C\uDDF0",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["createur"],
    french: false,
    artisanal: true,
    description: "Titane fabriqu\u00E9 main au Japon, plus de 100 \u00E9tapes.",
  },
  {
    name: "Veronika Wildgruber",
    slug: "veronika-wildgruber",
    image: "/images/marques/veronika-wildgruber.png",
    heroImage: "/images/boutique/veronika.png",
    country: "Allemagne",
    countryFlag: "\uD83C\uDDE9\uD83C\uDDEA",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["createur", "tendance"],
    french: false,
    featured: true,
    badge: "Nouveaut\u00E9",
    description: "Minimalisme allemand, laur\u00E9ate du Silmo d\u2019Or 2017 et 2023.",
  },
  {
    name: "Prodesign Eyewear",
    slug: "prodesign-eyewear",
    image: "/images/marques/prodesign.jpg",
    heroImage: "/images/produits/prodesign.jpg",
    country: "Danemark",
    countryFlag: "\uD83C\uDDE9\uD83C\uDDF0",
    priceRange: "\u20AC\u20AC",
    categories: ["createur"],
    french: false,
    description: "Design scandinave \u00E9pur\u00E9 depuis 1973.",
  },
  {
    name: "Jos Eschenbach",
    slug: "jos-eschenbach",
    image: "/images/marques/jos-eschenbach.jpg",
    country: "Allemagne",
    countryFlag: "\uD83C\uDDE9\uD83C\uDDEA",
    priceRange: "\u20AC\u20AC",
    categories: ["createur"],
    french: false,
    description: "Fabricant allemand, plus de 100 ans d\u2019expertise en titane.",
  },

  // MODE & TENDANCE
  {
    name: "Ray-Ban",
    slug: "ray-ban",
    image: "/images/marques/ray-ban.png",
    heroImage: "/images/produits/ray-ban-stories.jpg",
    country: "USA",
    countryFlag: "\uD83C\uDDFA\uD83C\uDDF8",
    priceRange: "\u20AC\u20AC",
    categories: ["luxe", "tendance"],
    french: false,
    description: "Marque iconique fond\u00E9e en 1937, Aviator et Wayfarer intemporels.",
  },
  {
    name: "Carrera",
    slug: "carrera",
    image: "/images/marques/carrera.png",
    heroImage: "/images/produits/carrera-ducati.jpg",
    country: "Autriche",
    countryFlag: "\uD83C\uDDE6\uD83C\uDDF9",
    priceRange: "\u20AC\u20AC",
    categories: ["sport", "tendance"],
    french: false,
    description: "H\u00E9ritage automobile et sportif depuis 1956.",
  },
  {
    name: "Eyewear by David Beckham",
    slug: "eyewear-by-david-beckham",
    image: "/images/marques/david-beckham.webp",
    heroImage: "/images/produits/dbe-opt.webp",
    country: "UK",
    countryFlag: "\uD83C\uDDEC\uD83C\uDDE7",
    priceRange: "\u20AC\u20AC",
    categories: ["tendance"],
    french: false,
    description: "Style britannique classique, fabrication italienne.",
  },
  {
    name: "Paul & Joe",
    slug: "paul-joe",
    image: "/images/marques/paul-joe.png",
    heroImage: "/images/produits/paul-joe.png",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC",
    categories: ["createur", "tendance"],
    french: true,
    description: "Montures f\u00E9minines et color\u00E9es, imprim\u00E9s floraux.",
  },
  {
    name: "Eleven Paris",
    slug: "eleven-paris",
    image: "/images/marques/eleven-paris.jpg",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC",
    categories: ["createur", "tendance"],
    french: true,
    description: "C\u00E9l\u00E8bre pour \u2018Life is a Joke\u2019, style urbain et d\u00E9cal\u00E9.",
  },
  {
    name: "Izipizi",
    slug: "izipizi",
    image: "/images/marques/izipizi.jpg",
    heroImage: "/images/produits/izipizi.jpg",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC",
    categories: ["tendance", "enfant"],
    french: true,
    description: "Ph\u00E9nom\u00E8ne de mode accessible pr\u00E9sent dans 90 pays.",
  },

  // SPORT & OUTDOOR
  {
    name: "Oakley",
    slug: "oakley",
    image: "/images/marques/oakley.jpg",
    heroImage: "/images/produits/oakley-hero.jpg",
    country: "USA",
    countryFlag: "\uD83C\uDDFA\uD83C\uDDF8",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["sport"],
    french: false,
    description: "R\u00E9f\u00E9rence mondiale de la lunette sport depuis 1975.",
  },
  {
    name: "Julbo",
    slug: "julbo",
    image: "/images/marques/julbo.png",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC",
    categories: ["sport", "enfant"],
    french: true,
    description: "Sp\u00E9cialiste montagne fond\u00E9 en 1888 \u00E0 Morez, verres REACTIV.",
  },
  {
    name: "Boll\u00E9",
    slug: "bolle",
    image: "/images/marques/bolle.webp",
    heroImage: "/images/produits/bolle-icarus.webp",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC",
    categories: ["sport"],
    french: true,
    description: "Leader lunettes sport outdoor depuis 1888 \u00E0 Oyonnax.",
  },
  {
    name: "C\u00E9b\u00E9",
    slug: "cebe",
    image: "/images/marques/cebe.jpg",
    heroImage: "/images/produits/cebe-baxter.jpg",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC",
    categories: ["sport", "enfant"],
    french: true,
    description: "Pionni\u00E8re des lunettes de sport, excellente gamme enfant.",
  },
  {
    name: "Nike",
    slug: "nike",
    image: "/images/marques/nike.jpg",
    heroImage: "/images/produits/nike-running.jpg",
    country: "USA",
    countryFlag: "\uD83C\uDDFA\uD83C\uDDF8",
    priceRange: "\u20AC\u20AC",
    categories: ["sport"],
    french: false,
    description: "Montures sport l\u00E9g\u00E8res et r\u00E9sistantes, verres MAX Optics.",
  },
  {
    name: "Demetz",
    slug: "demetz",
    image: "/images/marques/demetz.jpg",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC",
    categories: ["sport", "enfant"],
    french: true,
    description: "Sp\u00E9cialiste fran\u00E7ais de l\u2019optique sportive depuis plus de 60 ans.",
  },

  // ENFANT
  {
    name: "Lookkino",
    slug: "lookkino",
    image: "/images/marques/lookkino.jpg",
    heroImage: "/images/produits/lookkino.jpg",
    country: "Italie",
    countryFlag: "\uD83C\uDDEE\uD83C\uDDF9",
    priceRange: "\u20AC\u20AC",
    categories: ["enfant"],
    french: false,
    description: "Collection enfants italienne, mat\u00E9riaux hypoallerg\u00E9niques.",
  },
];
