export type BrandCategory =
  | "luxe"
  | "createur"
  | "sport"
  | "enfant"
  | "eco"
  | "tendance";

export type PriceRange = "\u20AC" | "\u20AC\u20AC" | "\u20AC\u20AC\u20AC" | "\u20AC\u20AC\u20AC\u20AC";

export interface Brand {
  name: string;
  slug: string;
  image: string | null;
  heroImage?: string;
  country: string;
  countryFlag: string;
  priceRange: PriceRange;
  categories: BrandCategory[];
  french: boolean;
  featured?: boolean;
  badge?: "Tendance" | "Nouveaut\u00E9" | "Exclusivit\u00E9";
  description?: string;
  website?: string;
  ecoResponsible?: boolean;
  artisanal?: boolean;
}

export const categoryLabels: Record<BrandCategory, string> = {
  luxe: "Luxe",
  createur: "Cr\u00E9ateurs",
  sport: "Sport & Outdoor",
  enfant: "Enfant",
  eco: "\u00C9co-responsable",
  tendance: "Tendance",
};

export function getCountryCode(country: string): string {
  const map: Record<string, string> = {
    France: "FR",
    Italie: "IT",
    USA: "US",
    UK: "GB",
    Allemagne: "DE",
    Autriche: "AT",
    Espagne: "ES",
    Danemark: "DK",
  };
  return map[country] || country.slice(0, 2).toUpperCase();
}

export const brands: Brand[] = [
  // LUXE & CRÉATEURS
  {
    name: "Gucci",
    slug: "gucci",
    image: "/images/marques/gucci.webp",
    heroImage: "/images/produits/gucci-campagne.webp",
    country: "Italie",
    countryFlag: "\uD83C\uDDEE\uD83C\uDDF9",
    priceRange: "\u20AC\u20AC\u20AC\u20AC",
    categories: ["luxe"],
    french: false,
    description: "Maison de luxe italienne fond\u00E9e en 1921. Lunettes au design audacieux et logo double-G iconique.",
  },
  {
    name: "Chlo\u00E9",
    slug: "chloe",
    image: "/images/marques/chloe.webp",
    heroImage: "/images/produits/chloe-tendance.webp",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC\u20AC\u20AC",
    categories: ["luxe"],
    french: true,
    description: "Gaby Aghion choisit le nom Chloé pour baptiser sa marque en 1952 par rapport à sa consonance chaude et féminine. D’origine égyptienne, cette parisienne souhaitait que sa marque soit à l’image du Paris des années 50 ; jeune, moderne et plein d’audace. C’est ainsi que se définit la collection de lunettes Chloé. Les modèles sont destinés principalement aux femmes de plus de 35 ans passionnées de mode.",
  },
  {
    name: "Céline Paris",
    slug: "celine-paris",
    image: "/images/marques/celine-paris.webp",
    country: "France",
    countryFlag: "🇫🇷",
    priceRange: "€€€€",
    categories: ["luxe"],
    french: true,
    description: "Fondée en 1945 par Céline Vipiana, la maison parisienne Céline incarne le chic à la française. La collection de lunettes, empreinte d’un minimalisme sophistiqué, se distingue par des lignes épurées et des formes iconiques, du modèle pantos au plus audacieux oversized. Emblème d’une élégance intemporelle, Céline habille les regards avec une sensibilité mode unique, plebiscitée par les célébrités du monde entier. Chaque monture est le fruit d’un savoir-faire italien d’exception, combinant matières premium et finitions soignées.",
  },
  {
    name: "Oliver Peoples",
    slug: "oliver-peoples",
    image: "/images/marques/oliver-peoples.webp",
    heroImage: "/images/marques/oliver-peoples.webp",
    country: "USA",
    countryFlag: "\uD83C\uDDFA\uD83C\uDDF8",
    priceRange: "\u20AC\u20AC\u20AC\u20AC",
    categories: ["luxe", "createur"],
    french: false,
    description: "Oliver Peoples, est une grande histoire de famille. C’est l’histoire de deux frères, Larry et Dennis Light qui lors de l’achat de leur première boutique d’optique en 1986 à Hollywood, sur le mythique Sunset Boulevard, font l’acquisition d’une collection de lunettes vintage américaines des années 1940-1960 pour lancer leur magasin. Lors du déballage de la collection les deux frères y découvrent un reçu au nom d’Oliver Peoples, sans doute le dernier propriétaire ou le distributeur de ces lunettes. Ces milliers de lunettes découvertes étaient fabriquées par des fournisseurs américains, mais n’avaient encore jamais été portées. En hommage à ce signe du destin, ils décidèrent d’appeler la collection Oliver Peoples, et c’est le début de l’aventure. Cette marque vintage américaine aura su résister à toutes les modes. Actuellement cette marque de lunettes est très en vogue et branchée, la collection comprend des montures solaires mais également des lunettes de vue à accessoiriser avec des clips solaires. Tout visage a son modèle Oliver peoples qui lui convient ! Son succès a été total lorsque Andy Warhol a porté un modèle de la collection et qu’il a très vite été imité par de nombreuses stars américaines.",
  },
  {
    name: "Persol",
    slug: "persol",
    image: "/images/marques/persol.webp",
    heroImage: "/images/marques/persol.webp",
    country: "Italie",
    countryFlag: "\uD83C\uDDEE\uD83C\uDDF9",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["luxe"],
    french: false,
    description: "L’histoire de Persol commence en 1917 en Italie à Turin quand le photographe et inventeur Giuseppe Ratti crée l’entreprise « Ratti » pour fabriquer des lunettes de protection pour les pilotes (aussi bien de trams que de voitures de courses). Giuseppe Ratti veut des lunettes avant-gardistes. Il est rapidement sollicité par l’armée qui adopte le modèle « Protector ». Puis la popularité des modèles de lunettes qu’il invente s’étend auprès des civils. Elle devient internationale lorsque les starlettes et stars adoptent également ses lunettes. Riche de treize ans d’innovations, « Ratti » devient Persol en 1930. Le nom de Persol vient de la contraction des mots « per il sol », c’est-à-dire « pour le soleil ». Avant même Steve McQueen, c’est le grand Marcello Mastroianni qui a popularisé les Persol avec sa participation au film « La Dolce Vita », le légendaire film réalisé par Federico Fellini en 1960.",
  },
  {
    name: "MOSCOT Eyewear",
    slug: "moscot-eyewear",
    image: "/images/marques/moscot.webp",
    heroImage: "/images/produits/moscot-miltzen.webp",
    country: "USA",
    countryFlag: "\uD83C\uDDFA\uD83C\uDDF8",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["createur", "tendance"],
    french: false,
    featured: true,
    badge: "Tendance",
    description: "Chez Optique Queuleu à Metz, nous sommes fiers de vous présenter la marque MOSCOT EYEWEAR, menée par la famille Moscot depuis cinq générations. L’entreprise de lunettes de luxe éponyme est une incontournable de la ville de New York, et en particulier du Lower East Side. Depuis sa création, il y a plus d’un siècle, la marque s’est fait un nom et l’histoire de ses débuts ne fait qu’ajouter à sa légende.",
  },
  {
    name: "Isabel Marant",
    slug: "isabel-marant",
    image: "/images/marques/isabel-marant.webp",
    heroImage: "/images/produits/isabel-marant-campagne.webp",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["luxe", "createur"],
    french: true,
    description: "Style audacieux m\u00EAlant luxe fran\u00E7ais et \u00E9l\u00E9gance contemporaine.",
  },
  {
    name: "Pierre Cardin",
    slug: "pierre-cardin",
    image: "/images/marques/pierre-cardin.webp",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC",
    categories: ["tendance"],
    french: true,
    description: "Maison de mode fran\u00E7aise fond\u00E9e en 1950, design avant-gardiste.",
  },

  // CRÉATEURS FRANÇAIS
  {
    name: "Caroline Abram",
    slug: "caroline-abram",
    image: "/images/marques/caroline-abram.webp",
    heroImage: "/images/produits/caroline-abram-patchwork.webp",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC",
    categories: ["createur"],
    french: true,
    description: "Cr\u00E9atrice parisienne, montures r\u00E9tro-glamour inspir\u00E9es des ann\u00E9es 50-60.",
  },
  {
    name: "Jean-Fran\u00E7ois Rey",
    slug: "jean-francois-rey",
    image: "/images/marques/jean-francois-rey.webp",
    heroImage: "/images/produits/jfrey.webp",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["createur"],
    french: true,
    artisanal: true,
    description: "Le nom Jean-François Rey c’est l’histoire de Joëlle et Jean-François, deux passionnés qui fondent leur marque en 1995. Les montures JF REY, sont tout d’abord un véritable travail sur les matériaux. Un assemblage minutieux de manière à proposer des produits d’une grande légèreté, élégants, faciles à porter et confortables. Les matières utilisées sont le métal, l’acétate, mais aussi le bois, le titane et le carbone. La marque dispose de sa propre usine de fabrication dans le Jura (Ellaps) qui lui permet de fabriquer ses propres produits en métal. Ils proposent également un travail très spécifique sur la couleur, qui est véritablement inscrite dans leur ADN, on trouvera dans la collection JF REY, de belles plaques d’acétates colorées.",
  },
  {
    name: "Nathalie Blanc",
    slug: "nathalie-blanc",
    image: "/images/marques/nathalie-blanc.webp",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["createur"],
    french: true,
    artisanal: true,
    description: "Audacieuse et passionnée, Nathalie Blanc est une créatrice parisienne qui met tout son esprit avant-gardiste et son talent pour créer des montures de lunettes d’exception. Depuis la naissance de sa marque, elle n’a qu’un mantra : le Made in France ! S’engageant de tout son cœur pour défendre un artisanat hexagonal d’excellence, elle choisit les meilleurs ateliers pour manufacturer ses lunettes raffinées et délicates, harmonie parfaite entre l’œil, le style et la matière : c’est en Normandie et dans le Jura, berceau de la lunetterie française, que naissent ces merveilleuses créations !",
  },
  {
    name: "Monsieur Blanc",
    slug: "monsieur-blanc",
    image: "/images/marques/monsieur-blanc.webp",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["createur"],
    french: true,
    artisanal: true,
    description: "Collection masculine de Maison Nathalie Blanc, titane japonais.",
  },
  {
    name: "Tarian",
    slug: "tarian",
    image: "/images/marques/tarian.webp",
    heroImage: "/images/produits/tarian.webp",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["createur"],
    french: true,
    artisanal: true,
    description: "Lunettes atypiques et élégantes Tarian Le nom de Jeremy Tarian vous dit peut-être quelque chose, et pour cause ! Celui-ci n’est rien d’autre que le fils du célèbre lunetier créateur des années 80 Alain Mikli, connu pour ses lunettes à la fois mode et fantasques. Jérémy Tarian, de nombreuses récompenses En digne successeur, Jeremy Tarian a hérité de la passion de son père pour les lunettes. Designer atypique, les modèles qu’il crée sont aussi originaux qu’élégants. Son talent a par ailleurs été récompensé plusieurs fois par le Silmo d’or, prix prestigieux décerné chaque année à Paris aux meilleurs lunetiers créateurs.",
  },
  {
    name: "Roussilhe",
    slug: "roussilhe",
    image: "/images/marques/roussilhe.webp",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC",
    categories: ["createur"],
    french: true,
    artisanal: true,
    description: "Manufacture du Jura depuis 1979, label Origine France Garantie.",
  },
  {
    name: "Sarah Lavoine",
    slug: "sarah-lavoine",
    image: "/images/marques/sarah-lavoine.webp",
    heroImage: "/images/produits/sarah-lavoisine-roussilhe.webp",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["createur"],
    french: true,
    artisanal: true,
    ecoResponsible: true,
    description: "Collaboration avec Ateliers Roussilhe, ac\u00E9tate biologique.",
  },
  {
    name: "Peter and May",
    slug: "peter-and-may",
    image: "/images/marques/peter-and-may.webp",
    heroImage: "/images/produits/peter-and-may.webp",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["createur"],
    french: true,
    description: "La collection de lunettes Peter and May se caractérise par son approche artisanale et son engagement envers le design et la qualité. Fondée par Laura Le Bihan et Xavier Matrand, la marque se distingue par ses créations uniques qui mêlent esthétique contemporaine et savoir-faire traditionnel. Les lunettes Peter and May sont reconnues pour leur utilisation de matériaux de haute qualité, comme l’acétate de cellulose et le métal précieux, ainsi que pour leurs finitions soignées. Chaque pièce est conçue avec une attention particulière portée aux détails, offrant une variété de formes, de couleurs et de textures pour répondre aux goûts variés des porteurs. La collection s’étend des montures classiques revisitées avec une touche moderne aux designs plus avant-gardistes, soulignant ainsi la personnalité et le style individuel. La marque se distingue également par son engagement envers la durabilité, cherchant à réduire son impact environnemental à travers des choix de production et de matériaux responsables. Peter and May s’associe à des artisans expérimentés et utilise des techniques traditionnelles pour créer des lunettes qui ne sont pas seulement belles, mais également durables et confortables à porter. En résumé, la collection de lunettes Peter and May représente un mariage réussi entre design contemporain, artisanat de qualité et responsabilité environnementale.",
  },
  {
    name: "Noego",
    slug: "noego",
    image: "/images/marques/noego.webp",
    heroImage: "/images/produits/noego-parasite.webp",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["createur"],
    french: true,
    description: "L’originalité jusqu’au bout du nez Noego est la collection de montures du créateur Hugo Martin, également concepteur de la marque Parasite. Les lunettes Noego sont contemporaines et sophistiquées, elles conviennent aux personnes qui ont un style original et singulier. La ligne créatrice de Noego est avant-gardiste et propose un design hors du commun, pensé avec des matériaux innovants et des couleurs inédites. La qualité de fabrication et de finition des lunettes Noego fait de ces montures un produit optique haut de gamme.",
  },
  {
    name: "Oxibis",
    slug: "oxibis",
    image: "/images/marques/oxibis.webp",
    heroImage: "/images/produits/oxibis.webp",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC",
    categories: ["createur"],
    french: true,
    description: "C’est dans le bassin des lunetiers français, dans le Jura, qu’Oxibis Group® voit le jour en 1992. C’est en défendant des valeurs comme la créativité et la qualité qu’Oxibis Group® a pu se développer et s’imposer parmi les grands noms de la lunetterie. Les lunettes Oxibis® sont pétillantes et audacieuses, les couleurs sont sélectionnées avec choix pour souligner au mieux les formes des montures. Oxibis® s’inspirent des tendances actuelles et les réinterprètent. Les lunettes Oxibis®, aux couleurs dynamiques, sont le reflet de l’expertise du groupe. Les hommes et les femmes à la recherche de lunettes éclatantes, où couleurs et formes sont en parfaites harmonie trouveront leur bonheur avec les montures Oxibis®.",
  },
  {
    name: "Dilem",
    slug: "dilem",
    image: "/images/marques/dilem.webp",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC",
    categories: ["createur"],
    french: true,
    description: "Une nouvelle philosophie : la trilogie ! 3, 2, 1… Go ! Prenant un virage à 180 degrés, la marque Dilem® voit maintenant la vie, ou plutôt ses collections, en trois dimensions. Désormais, chaque monture sera déclinée en 3 niveaux de créativité. Un concept « Show » extravagant, tiré de l’inspiration sans filtre des designers, et produit en édition limitée : l’aîné est le plus déjanté ! Dans sa lignée, des modèles « Studio », au design créatif légèrement assagi : le cadet conserve un beau brin de folie ! Derniers-nés qui ne sauraient se faire oublier, des modèles « Live ! », plus sobres, pour un look classique indémodable : tel le petit poucet, le benjamin est toujours le plus raisonnable ! Les trois premières séries, 3A, 3B et 3C laissent déjà présager du meilleur : si 3A nous ramène à la fantaisie vintage des sixties avec ses acétates sculptées, 3B sur les pas des plus grands alpinistes nous invite à escalader les glaciers… quant à 3C, il nous entraîne par un fil perpétuel dans un tourbillon chic et doré. Les quatre séries suivantes 3 E, 3F, 3G et 3H confirment la tendance : 3 E avec sa forme pilote nous conduit par-delà l’horizon, quand 3F laisse ondoyer ses volutes de métal coloré… 3G quant à elle prend des airs de boule à facette disco, et 3H jongle entre pureté et originalité avec sa visière perforée ! Une chose est sûre : vous allez les adorer ! L’ADN de Dilem® Tressant trois fils indissociables, la firme tricolore tricote un style inimitable… La liberté Des designers totalement libres de donner vie à leur imagination, sans limites. Libres de s’exprimer, de créer pour faire fleurir la diversité ! La qualité Des lunettes haut de gamme, sculptées dans des matières premières de premier choix : des montures légères et confortables que tout le monde vous enviera. Le choix Avec Dilem®, pour les porteurs aussi les options se déclinent à l’infini… Choix du modèle, bien sûr, mais également celui de le personnaliser. Avec un concept breveté de branches interchangeables à l’envi, les créations de la marque s’adaptent en un clin d’œil. Pour sortir du train-train quotidien, couleurs, motifs et matériaux se troquent sans tracas, tragédie, ni trémolos !",
  },
  {
    name: "Woow",
    slug: "woow",
    image: "/images/marques/woow.gif",
    heroImage: "/images/produits/woow.gif",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC",
    categories: ["createur", "tendance"],
    french: true,
    description: "Collection ludique avec messages cach\u00E9s au bout des branches.",
  },
  {
    name: "Osmose",
    slug: "osmose",
    image: "/images/marques/osmose.webp",
    heroImage: "/images/produits/osmose.webp",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC",
    categories: ["createur"],
    french: true,
    description: "Osmose, un concept original et innovant dans le monde la lunette basé sur la découpe de verres stylisés. La marque OSMOSE se décline en 2 collections de montures percées : la collection Boréale et la collection Australe.",
  },
  {
    name: "Minima",
    slug: "minima",
    image: "/images/marques/minima.webp",
    heroImage: "/images/produits/minima-femme.webp",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["createur"],
    french: true,
    description: "Une philosophie de la performance Minima, cultive la différence, pointe la performance, et vise l’excellence. En un mot, la marque s’adapte en permanence. Pour repousser toujours plus les limites du possible. Pour concevoir des lunettes qui assurent le bien-être de ceux qui les portent. Toutes les collections témoignent de cette exigence constante d’innovation et de technicité, avec des lunettes aussi légères que de qualité, aussi fiables que durables. Le tout marqué du style Minima : épuré et soigné, tout “simplement” élégant. Chez Minima, il y a du choix Pour les hommes et les femmes, les lunettes rétros côtoient les colorées, les ultralight se jouent des XXL, les précieuses font de l’œil aux invisibles, le titane fait valoir son ultralégèreté, quand l’acétate révèle ses couleurs et le métal argue de sa finesse… Avec une gamme de plus d’une vingtaine de références pour adultes, en optique et en solaire, tous les styles sont chez Minima. Cette performance technique est doublée d’une esthétique et d’un design innovants.",
  },
  {
    name: "Brett Eyewear",
    slug: "brett-eyewear",
    image: "/images/marques/brett-eyewear.webp",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC",
    categories: ["createur"],
    french: true,
    artisanal: true,
    description: "BRETT trouve son essence dans les films et séries culte des années 70. Un vent de liberté souffle sur cette période qui se traduit par l’émergence de nouveaux styles vestimentaires et musicaux. Nos modèles s’inspirent des exploits fictifs et réels des héros et pilotes légendaires qui n’hésitaient pas à casser les codes, souvent au mépris de leur vie, mais toujours avec flegme et élégance. Même si elle puise sa source d’inspiration dans le passé, notre collection s’inscrit dans le présent avec des choix en matière de design et de fabrication qui lui confèrent son propre ADN.",
  },
  {
    name: "Cl\u00E9mence et Margaux",
    slug: "clemence-et-margaux",
    image: "/images/marques/clemence-et-margaux.webp",
    heroImage: "/images/produits/clemence-margaux.webp",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC",
    categories: ["createur"],
    french: true,
    description: "Née de la complicité de deux sœurs… À l’origine de cette ligne de lunettes qui sonne comme une griffe de prêt-à-porter tendance, il y a le talent et surtout la complicité de deux sœurs. L’aventure commence, en effet, le jour où Margaux, jeune femme passionnée de mode, imagine des modèles de lunettes pour Clémence qui est mal-voyante. Très vite, cette dernière apporte sa propre inspiration et participe au design : la marque Clémence & Margaux est née ! Aujourd’hui, ce duo de charme conçoit des montures à l’architecture à la fois contemporaine et rétro, où se mêlent fraicheur, glamour, fantaisie et souci du détail, celui qui fait la différence et rend unique. À travers leurs créations, Clémence et Margaux s’adressent à des femmes modernes et pleines d’esprit : des femmes qui leur ressemblent, en quelque sorte. Clémence et Margaux, les deux jeunes sœurs créatrices de la ligne éponyme, proposent des modèles de lunettes à l’esprit unique, à l’image de leur tandem. La force de cette collection de la marque CCO repose sur la complicité magique de Clémence et Margaux, mais aussi sur les domaines où les deux jeunes femmes puisent leur inspiration : la mode et le design.",
  },
  {
    name: "Ancet & Fayolle",
    slug: "ancet-fayolle",
    image: "/images/marques/ancet-fayolle.webp",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["createur"],
    french: true,
    artisanal: true,
    description: "Ancet & Fayolle est une marque de lunetterie française de prestige, reconnue pour son artisanat d’exception, son engagement envers la qualité et son design innovant. Chaque paire de lunettes est une œuvre d’art, fabriquée à la main à Lyon, incarnant le luxe et la sophistication à la française",
  },
  {
    name: "Plein les Mirettes",
    slug: "plein-les-mirettes",
    image: "/images/marques/plein-les-mirettes.webp",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["createur"],
    french: true,
    artisanal: true,
    description: "Fondée en 2011, la marque Plein les Mirettes revendique une fabrication exclusivement française et artisanale. Chaque monture à la fois simple et raffinée, composée d’acétate de cellulose biodégradable, doit rehausser la personnalité de chaque femme. Les détails des montures font de chaque monture un objet unique.",
  },
  {
    name: "T\u00EAte \u00E0 Lunettes",
    slug: "tete-a-lunettes",
    image: "/images/marques/tete-a-lunettes.webp",
    heroImage: "/images/marques/tete-a-lunettes.webp",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC",
    categories: ["enfant"],
    french: true,
    description: "Tête à Lunettes fait écho à la ligne Caroline Abram dédiée aux adultes : couleurs dynamiques et acétates translucides, s’adressant aux enfants à partir de trois ou quatre ans.",
  },

  // ÉCO-RESPONSABLE
  {
    name: "Friendly Frenchy",
    slug: "friendly-frenchy",
    image: "/images/marques/friendly-frenchy.webp",
    heroImage: "/images/produits/friendly-frenchy.webp",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC",
    categories: ["eco", "createur", "tendance"],
    french: true,
    ecoResponsible: true,
    artisanal: true,
    featured: true,
    badge: "Nouveaut\u00E9",
    description: "Pionni\u00E8re des lunettes en coquillages recycl\u00E9s, 0% p\u00E9trole, 100% fran\u00E7aise.",
  },
  {
    name: "Cl\u00E9ment Lunetier",
    slug: "clement-lunetier",
    image: "/images/marques/clement-lunetier.webp",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["eco", "createur"],
    french: true,
    ecoResponsible: true,
    artisanal: true,
    description: "Passionnés par l’optique, Vincent et Ben décident de fonder leur entreprise en 2016. Ils lancent ainsi leur première collection, fabriquée dans leur atelier strasbourgeois, et nomment la marque créateur d’après le prénom du fils de Vincent, Clément, qui accaparait toute leur attention durant leurs réunions. La principale source d’inspiration de leur création est la passion pour les avions-planeurs de Ben, qui leur permet d’inventer des lunettes aériennes et dynamiques !",
  },
  {
    name: "Shelter",
    slug: "shelter",
    image: "/images/marques/shelter.webp",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["eco", "createur"],
    french: true,
    ecoResponsible: true,
    artisanal: true,
    description: "A l’origine de Shelter, Créateur Lunetier, un pari fou : celui de créer des lunettes en bois élégantes et racées, made in France, sans perdre de vue le confort et la légèreté. Été 2013, à Annecy, 5 amis fondateurs jettent la première pierre de ce qui deviendra la marque Shelter. Leur ambition : créer une marque de lunettes en bois qui soit créative, de manufacture Française et vertueuse pour l’environnement. Dès le début, Shelter travaille main dans la main avec Marotte, spécialiste des placages de bois très haut de gamme. Son savoir-faire et la richesse de sa collection d’essences permettent d’apporter à chaque monture une beauté singulière et une qualité exceptionnelle. 5 ans plus tard, Shelter s’impose comme une référence en terme de création lunetière en bois.",
  },
  {
    name: "Eco",
    slug: "eco",
    image: "/images/marques/eco.webp",
    country: "USA",
    countryFlag: "\uD83C\uDDFA\uD83C\uDDF8",
    priceRange: "\u20AC\u20AC",
    categories: ["eco"],
    french: false,
    ecoResponsible: true,
    description: "95% du métal des montures est recyclé Eco propose des lunettes biosourcées fabriquées à partir d’huile de ricin. Un matériau léger, confortable et respectueux de l’environnement. Autre spécificité des montures : elles sont dotées d’aimants intégrés invisibles, de manière à positionner facilement des clips solaires magnétiques.​ La nouvelle collection Eco se compose de 11 modèles optiques avec des clips tendances et 4 solaires équipées de verres polarisés. Par ailleurs, la marque indique que 95% du métal de ses montures est recyclé. Cela représente une économie importante en ressources naturelles.",
  },
  {
    name: "La Brique & la Violette",
    slug: "la-brique-et-la-violette",
    image: "/images/marques/la-brique-et-la-violette.webp",
    heroImage: "/images/produits/collection.webp",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC",
    categories: ["eco", "createur", "tendance"],
    french: true,
    ecoResponsible: true,
    artisanal: true,
    featured: true,
    badge: "Exclusivit\u00E9",
    description: "Marine et Romain deux opticiens à la créativité débordante ouvrent leur première boutique de lunettes en 2012. Ils y créent des montures sur mesure, de leurs propres mains, pour les beaux yeux de leurs clients. Leur première collection La Brique et la Violette est le fruit de ces années de passion, de rencontres et d’expériences. Les montures La Brique et la Violette sont fabriquées et assemblées dans un l’atelier familial à 15 minutes de Toulouse. Fabriqué veut dire découpé, usiné, poncé, poli, riveté, limé, ajusté…, et pas simplement emballé. Plus de 40 étapes sont nécessaires à la confection d’une monture. Toutes les montures sont faites en acétate de cellulose de chez MAZUCCHELLi, 100% issu de leur production italienne.",
  },
  {
    name: "Modo",
    slug: "modo",
    image: "/images/marques/modo.webp",
    heroImage: "/images/produits/modo-titanium.webp",
    country: "USA",
    countryFlag: "\uD83C\uDDFA\uD83C\uDDF8",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["eco", "createur"],
    french: false,
    ecoResponsible: true,
    description: "Née il y a plus de 15 ans dans le quartier de Soho à New York, Modo n’a cessé de se transformer et de donner vie à ses partenaires. Ne se limitant pas à son propre environnement lunetier, la marque américaine conçoit, fabrique et distribue les réalisations de nombreux acteurs gravitant autour de l’optique. Créateurs, designers… chacun trouve sa place sur le chemin de l’innovation. Très contemporaine dans son approche, Modo s’est donné une ligne de conduite en harmonie avec ses valeurs. Avec un souci permanent de proposer une production durable et écoresponsable, le fondateur de la marque a souhaité construire son développement en s’appuyant sur des initiatives sociales fortes : bien qu’ayant des ambitions internationales, Modo met un point d’honneur à placer l’être humain au centre de ses préoccupations. Suivre les tendances de la mode n’empêche pas d’être lucide sur les réalités de ce monde. Montures issues de matériaux recyclés ou bio, programme de plantation d’un arbre pour chaque paire de lunettes achetée, aide aux enfants malvoyants… Modo a choisi de réunir expansion économique et actions humanitaires. Une belle façon de créer et de vivre avec son temps.",
  },

  // CRÉATEURS INTERNATIONAUX
  {
    name: "Etnia Barcelona",
    slug: "etnia-barcelona",
    image: "/images/marques/etnia-barcelona.webp",
    heroImage: "/images/produits/etnia-barcelona.webp",
    country: "Espagne",
    countryFlag: "\uD83C\uDDEA\uD83C\uDDF8",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["createur", "tendance"],
    french: false,
    featured: true,
    badge: "Tendance",
    description: "Ayant grandi dans les coulisses de l’usine de lunettes familiale, David Pellicier fonde Etnia Barcelona en 2001 avec la ferme intention de concrétiser son attrait pour la création. Nourri de 70 années d’expertise optique et encouragé par son grand-père qui apprécie sa modernité, le Catalan choisit son camp : il introduit de la couleur là où il n’y avait que du noir et du marron. Conscient de l’influence de son environnement, sous le soleil barcelonais, le lunetier puise son énergie dans le monde de l’art et de la mode. Précurseur de l’apport identitaire inhérent aux coloris, il travaille essentiellement l’acétate pour ses vertus chromatiques. Désireuse d’écrire son histoire au travers de collaborations créatives fécondes, Etnia Barcelona s’entoure de grands noms du graphisme et de la photographie pour donner vie à ses collections.Suivant les tendances et les inspirations saisonnières, Etnia Barcelona s’appuie sur une fabrication de haute qualité héritée de son passé. Avec des montures de lunettes affinées au fil du temps et un véritable goût pour les explorations colorées, la marque espagnole séduira les aficionados à la recherche d’accessoires affichant joie de vivre et sensibilité artistique.",
  },
  {
    name: "GIGI Studios",
    slug: "gigi-studios",
    image: "/images/marques/gigi-studios.webp",
    heroImage: "/images/produits/gigi-studios.webp",
    country: "Espagne",
    countryFlag: "\uD83C\uDDEA\uD83C\uDDF8",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["createur"],
    french: false,
    artisanal: true,
    description: "Maison familiale barcelonaise fond\u00E9e en 1962.",
  },
  {
    name: "Kaleos",
    slug: "kaleos",
    image: "/images/marques/kaleos.webp",
    country: "Espagne",
    countryFlag: "\uD83C\uDDEA\uD83C\uDDF8",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["createur", "tendance"],
    french: false,
    featured: true,
    badge: "Tendance",
    description: "Design contemporain, mat\u00E9riaux premium, assemblage artisanal.",
  },
  {
    name: "Talla Eyewear",
    slug: "talla-eyewear",
    image: "/images/marques/talla.webp",
    country: "Italie",
    countryFlag: "\uD83C\uDDEE\uD83C\uDDF9",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["createur"],
    french: false,
    artisanal: true,
    description: "Marque masculine de luxe, fabriqu\u00E9e main en Italie.",
  },
  {
    name: "Orgreen",
    slug: "orgreen",
    image: "/images/marques/orgreen.webp",
    country: "Danemark",
    countryFlag: "\uD83C\uDDE9\uD83C\uDDF0",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["createur"],
    french: false,
    artisanal: true,
    description: "Lunettes de luxe dans des matériaux haut de gamme, connues pour leur style caractéristique et leurs combinaisons de couleurs innovantes. Fondée à Copenhague en 1997, notre objectif est de concevoir des montures solides et intemporelles pour des personnes soucieuses de qualité dans le monde entier. ​Orgreen Optics est le meilleur du design danois. Les valeurs et les normes établies dans les années 50 et 60 par des designers de renommée internationale tels qu’Arne Jacobsen et Louis Poulsen – innovation, qualité, minimalisme et lignes épurées – se retrouvent dans toutes nos montures, mais avec une touche Orgreen, composée de détails uniques et de touches subtiles, inspirée de la culture de la rue, des sports extrêmes et des voitures classiques.",
  },
  {
    name: "Veronika Wildgruber",
    slug: "veronika-wildgruber",
    image: "/images/marques/veronika-wildgruber.webp",
    heroImage: "/images/boutique/veronika.webp",
    country: "Allemagne",
    countryFlag: "\uD83C\uDDE9\uD83C\uDDEA",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["createur", "tendance"],
    french: false,
    featured: true,
    badge: "Nouveaut\u00E9",
    description: "Découvrez les lunettes design Veronika Wildgruber chez Optique Queuleu à Metz : montures créatives, originales et haut de gamme. Essayez-les en boutique !",
  },
  {
    name: "Prodesign Eyewear",
    slug: "prodesign-eyewear",
    image: "/images/marques/prodesign.webp",
    heroImage: "/images/produits/prodesign.webp",
    country: "Danemark",
    countryFlag: "\uD83C\uDDE9\uD83C\uDDF0",
    priceRange: "\u20AC\u20AC",
    categories: ["createur"],
    french: false,
    description: "Design scandinave \u00E9pur\u00E9 depuis 1973.",
  },
  {
    name: "Jos Eschenbach",
    slug: "jos-eschenbach",
    image: "/images/marques/jos-eschenbach.webp",
    country: "Allemagne",
    countryFlag: "\uD83C\uDDE9\uD83C\uDDEA",
    priceRange: "\u20AC\u20AC",
    categories: ["createur"],
    french: false,
    description: "Plus de 100 ans d’expérience ont une valeur toute particulière à l’époque actuelle. Eschenbach Eyewear revient ainsi sur sa propre tradition pour créer une nouvelle marque : Jos. Eschenbach. Elle porte le nom du fondateur de l’entreprise et allie expérience et art professionnel de l’artisanat de plus de 102 ans dans le design et la fabrication des lunettes. Pour les hommes et les femmes pour qui l’esthétique et la vision comptent. ​Des montures équilibrées et innovantes Optique audacieuse, fort pouvoir innovant et tradition artisanale caractérisent le développement des lunettes de grande qualité Eschenbach Eyewear depuis le début. La nouvelle marque Jos. Eschenbach respecte particulièrement ces valeurs avec des lunettes traditionnelles et cependant modernes pour femmes et hommes et un design choisi. Eschenbach Eyewear transmet avec brio les traditions et les valeurs du passé à la nouvelle marque moderne. ​Des matières travaillées tout en sobriété Les coloris nordique sobres et les tons couleur terre naturels rendent les montures de lunettes Jos. Eschenbach particulièrement nobles et précieuses. Le béta-titane travaillé avec finesse offre un excellent confort de port ainsi qu’une grande solidité et des montures de lunettes aux propriétés élastiques.",
  },

  // MODE & TENDANCE
  {
    name: "Ray-Ban",
    slug: "ray-ban",
    image: "/images/marques/ray-ban.webp",
    heroImage: "/images/produits/ray-ban-stories.webp",
    country: "USA",
    countryFlag: "\uD83C\uDDFA\uD83C\uDDF8",
    priceRange: "\u20AC\u20AC",
    categories: ["luxe", "tendance"],
    french: false,
    description: "On ne présente plus cette marque plus que centenaire: ses origines remontent aux années 1850 lorsque Bausch et Lomb fondent leur société de recherche en ophtalmologie. Leur but est alors de créer des verres solaires, le nom Ray-Ban est d’ailleurs la contraction de Ray-banner, « bannir les rayons du soleil ». ​La marque naît en 1937 avec la sortie du modèle Aviator créé spécialement pour les pilotes de l’ U.S. Air Force. En 1952, Ray-Ban lance la Wayfarer, un modèle novateur qui rompt avec les traditionnelles lunettes en métal, rendues célèbres car Ray Charles les portait. En 1986 la Clubmaster, inspirée des lunettes de Malcolm X voit le jour. Elle a, comme les autres, un grand succès auprès des stars américaines, et reprend le style « browline » très en vogue sans les années 50. ​Que ce soit en monture optique ou solaire, Ray-Ban est toujours une valeur sûre.",
  },
  {
    name: "TAG Heuer",
    slug: "tag-heuer",
    image: "/images/marques/tag-heuer.webp",
    country: "Suisse",
    countryFlag: "🇨🇭",
    priceRange: "€€€€",
    categories: ["luxe", "sport"],
    french: false,
    description: "Fondée en 1860 par Edouard Heuer, la maison suisse TAG Heuer est une référence mondiale dans l’univers du chronométrage sportif et de l’horlogerie d’exception. Forte de cet héritage, la marque décline son ADN technique et racing dans une collection de lunettes haut de gamme, réputées pour leur innovation, leur légèreté et leur robustesse. Montures en titane, acétate premium ou caoutchouc nouvelle génération : chaque paire associe ingénierie de précision et design avant-gardiste, pour un style à la fois sportif, élégant et résolument contemporain.",
  },
  {
    name: "Paul & Joe",
    slug: "paul-joe",
    image: "/images/marques/paul-joe.webp",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC",
    categories: ["createur", "tendance"],
    french: true,
    description: "Sophie Albou, crée sa propre marque en 1995 : Paul & Joe®, reprenant les noms de ses deux fils. A l’origine, Paul & Joe® est une marque qui vient rompre les codes de la mode, elle se veut fashion mais pas trop. Jeune, fun et colorée, Paul & Joe® cultive la fraîcheur et la joie de vivre qui règnent à travers les collections. Sophie Albou lance, en 2006, une collection plus jeune et plus accessible, Paul & Joe Sister®. En 2009, Paul & Joe® ouvre une ligne Eyewear à destination des hommes et des femmes puis en 2012 des enfants. Les montures sont élégantes et acidulées, certaines ont un esprit vintage d’autres plutôt classique. La collection Paul & Joe® Eyewear est un véritables succès. ​Les montures Paul & Joe® sont élégantes et discrètes, elles sauront délicatement habiller votre regard par quelques touches de gaieté à l’image de la marque.",
  },
  {
    name: "Eleven Paris",
    slug: "eleven-paris",
    image: "/images/marques/eleven-paris.webp",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC",
    categories: ["createur", "tendance"],
    french: true,
    description: "Chez Optique Queuleu à Metz , nous vous proposons les lunettes Eleven Paris , une marque urbaine et tendance qui allie style et confort. Eleven Paris est connue pour son univers audacieux et décalé . Ses montures reprennent les codes de la mode contemporaine, avec des lignes modernes, des formes actuelles et une touche rebelle qui séduit ceux qui veulent se démarquer. Des lunettes pour affirmer votre style Les lunettes Eleven Paris sont idéales si vous recherchez : Des montures au design affirmé et original , Un look urbain et branché , Une combinaison parfaite entre mode et accessibilité . Votre opticien indépendant Optique Queuleu est revendeur officiel Eleven Paris . Venez découvrir la collection en magasin, essayez les modèles qui vous plaisent et bénéficiez de nos conseils personnalisés pour trouver la paire parfaite.",
  },
  {
    name: "Izipizi",
    slug: "izipizi",
    image: "/images/marques/izipizi.webp",
    heroImage: "/images/produits/izipizi.webp",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC",
    categories: ["tendance", "enfant"],
    french: true,
    description: "Lancée en 2010 par trois jeunes entrepreneurs français, la marque se distingue en proposant des lunettes de lecture remises au goût du jour, adaptées à la fois aux amoureux de vieux bouquins aux pages jaunies et aux amateurs des lectures numériques, que la lumière bleue des écrans fatigue. Mais Izipizi n’en reste pas là et innove avec des lunettes de soleil au design coloré et sympathique. Sportifs, vous pourrez parader avec sur les pistes enneigées ou les vagues californiennes, ou au contraire ; bénéficier d’une version avec correction pour une lecture paisible au soleil. Izipizi… un jeu de mot familier qui fait écho à l’expression britannique « easy peasy », que l’on pourrait traduire par « les doigts dans le nez ».",
  },
  {
    name: "Komono",
    slug: "komono",
    image: null,
    heroImage: "/images/produits/komono.webp",
    country: "Belgique",
    countryFlag: "🇧🇪",
    priceRange: "€€",
    categories: ["tendance"],
    french: false,
    description: "Fondée en 2009 à Anvers en Belgique, Komono (contraction de « koffie » et « mono ») est devenue une référence de l'accessoire au style affirmé et accessible. Ses lunettes de soleil mêlent design contemporain, formes audacieuses et palettes de couleurs travaillées, pour un look mode qui séduit autant les ados que les adultes. Montures rétro revisitées, masques sportifs ou silhouettes graphiques : Komono cultive une esthétique pointue à prix juste, devenue culte sur la scène lifestyle européenne.",
  },

  // SPORT & OUTDOOR
  {
    name: "Oakley",
    slug: "oakley",
    image: "/images/marques/oakley.webp",
    heroImage: "/images/produits/oakley-hero.webp",
    country: "USA",
    countryFlag: "\uD83C\uDDFA\uD83C\uDDF8",
    priceRange: "\u20AC\u20AC\u20AC",
    categories: ["sport"],
    french: false,
    description: "Les origines de la marque Oakley est une marque qui a vue le jour en 1975, créée par Jim JANNARD, mais d’où vient ce nom « Oakley » ? Il s’agit en réalité du nom de son chien qui avait pour habitude de se coucher au pied d’un chêne, ce qui donne littéralement en anglais « Oak-Ley ». Cependant à l’origine la marque Oakley n’avait aucun rapport avec le monde de l’optique et de la lunetterie et pour cause, Jim Jannard a commencé par fabriquer des poignées de guidon pour moto grâce à un nouveau matériau appelé « unobtainium ». Ce n’est qu’en 1984 que la marque décide de se lancer dans la lunetterie, lorsque son créateur découvre que le matériau innovant qu’il utilise pour les guidons de moto peut également servir à la création de lunettes. C’est véritablement à partir de cette date que la marque devient synonyme d’innovation, de technique et de performance. La première paire de lunettes qu’il créera s’appellera « O-Frame », avec un verre de forme cylindrique qui deviendra plus tard le logo de la marque. Cette monture a été conçue principalement pour la pratique de la moto (la marque garde malgré tout un attachement à cette pratique, après avoir fabriqué des guidons). La marque faisant de plus en plus parler d’elle, les sportifs commencent à s’y intéresser, notamment un cycliste : Greg Lemond, qui deviendra représentant de la marque et montera à trois reprises sur la première marche du podium du Tour de France en 1986, 1989 et 1990. Celui arborait à l’époque la monture Eyeshades, qui a été conçue sur la base des O-frames, en plus légères et plus performantes. Oakley et le grand public A l’origine réservée aux sportifs, la marque Oakley décide de se diversifier et de s’ouvrir au grand public en proposant des lunettes de soleil et des lunettes de vue, en gardant toutefois son style et sa philosophie.",
  },
  {
    name: "Julbo",
    slug: "julbo",
    image: "/images/marques/julbo.webp",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC",
    categories: ["sport", "enfant"],
    french: true,
    description: "Julbo tire tout simplement son nom de son créateur jurassien Jules Baud. Créée en 1888, l’entreprise a démarré en fabriquant des lunettes de protection pour les tailleurs de pierres. Vers le 20ème siècle, la marque se lance dans l’optique solaire en créant une paire de lunettes de soleil protégeant les yeux des cristalliers chamoniards en montagne. Avec le seul mot innovation en tête, Julbo a marqué une révolution en créant les premières lunettes de glacier. On peut désormais aller haut, les yeux bien protégés",
  },
  {
    name: "Rudy Project",
    slug: "rudy-project",
    image: null,
    heroImage: "/images/produits/rudy-project.webp",
    country: "Italie",
    countryFlag: "\uD83C\uDDEE\uD83C\uDDF9",
    priceRange: "\u20AC\u20AC",
    categories: ["sport"],
    french: false,
    description: "Fond\u00E9e en 1985 \u00E0 Tr\u00E9vise en Italie par Rudy Barbazza, Rudy Project s'est impos\u00E9e comme une r\u00E9f\u00E9rence mondiale de la lunette de sport et de performance. Cyclisme, running, triathlon, trail ou ski : chaque mod\u00E8le est pens\u00E9 pour la haute intensit\u00E9, avec des verres interchangeables, des traitements photochromiques et des montures ultra-l\u00E9g\u00E8res en Grilamid. Port\u00E9e par de nombreux athl\u00E8tes olympiques, la marque conjugue innovation technique, a\u00E9rodynamisme et protection optimale pour repousser vos limites.",
  },
  {
    name: "Boll\u00E9",
    slug: "bolle",
    image: "/images/marques/bolle.webp",
    heroImage: "/images/produits/bolle-icarus.webp",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC\u20AC",
    categories: ["sport"],
    french: true,
    description: "Marque française, Bollé est depuis 1888 un des leaders mondiaux sur le marché des lunettes de soleil, des masques et des casques. Reconnue et distribuée dans le monde entier, Bollé est une marque de sport réputée pour sa créativité et son design de pointe, créateur de tendance et repoussant constamment les limites de l’industrie.",
  },
  {
    name: "Vuarnet",
    slug: "vuarnet",
    image: "/images/marques/vuarnet.webp",
    country: "France",
    countryFlag: "🇫🇷",
    priceRange: "€€€",
    categories: ["sport", "luxe"],
    french: true,
    description: "Née en 1957 en Haute-Savoie, Vuarnet tire son nom du champion olympique Jean Vuarnet, médaillé d’or de descente à ski aux JO de 1960. La marque française est mondialement reconnue pour ses verres minéraux haute performance, réputés pour leur clarté exceptionnelle, leur résistance aux rayures et leur protection solaire inégalée. De l’aventure en haute montagne aux plages de la Riviera, les lunettes Vuarnet incarnent l’élégance française associée à une expertise technique de pointe. Montées à la main en France, chaque paire est le fruit d’un savoir-faire artisanal transmis depuis plus de soixante ans.",
    artisanal: true,
  },
  {
    name: "Demetz",
    slug: "demetz",
    image: "/images/marques/demetz.webp",
    country: "France",
    countryFlag: "\uD83C\uDDEB\uD83C\uDDF7",
    priceRange: "\u20AC",
    categories: ["sport", "enfant"],
    french: true,
    description: "Sp\u00E9cialiste fran\u00E7ais de l\u2019optique sportive depuis plus de 60 ans.",
  },

  // ENFANT
  {
    name: "Lookkino",
    slug: "lookkino",
    image: "/images/marques/lookkino.webp",
    country: "Italie",
    countryFlag: "\uD83C\uDDEE\uD83C\uDDF9",
    priceRange: "\u20AC\u20AC",
    categories: ["enfant"],
    french: false,
    description: "Collection enfants italienne, mat\u00E9riaux hypoallerg\u00E9niques.",
  },
];
